import io
import csv
import json
import datetime
from typing import List, Dict, Any, Optional

from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.pdfgen import canvas

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter


class NumberedCanvas(canvas.Canvas):
    """Canvas that computes total pages dynamically and adds footers with page numbers."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        
        # Header line & text on subsequent pages
        if self._pageNumber > 1:
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(36, 756, 576, 756)
            self.drawString(36, 762, "SENTRIDOSE — INDUSTRIAL DOSIMETER MONITORING REPORT")
            self.drawRightString(576, 762, datetime.datetime.utcnow().strftime("%Y-%m-%d UTC"))

        # Footer line & text
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(36, 40, 576, 40)
        
        footer_text = "CONFIDENTIAL — FOR AUTHORIZED SUPERVISOR SAFETY USE ONLY"
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawString(36, 28, footer_text)
        self.drawRightString(576, 28, page_text)
        self.restoreState()


def generate_pdf_report(
    report_metadata: Dict[str, Any],
    summary_data: Dict[str, Any],
    scans_data: List[Dict[str, Any]],
    filters: Dict[str, Any]
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=36,
        rightMargin=36,
        topMargin=48,
        bottomMargin=48
    )

    story = []
    styles = getSampleStyleSheet()

    # Custom Styles
    brand_style = ParagraphStyle(
        "BrandHeader",
        parent=styles["Heading1"],
        fontName="Helvetica-Bold",
        fontSize=20,
        leading=24,
        textColor=colors.HexColor("#0f172a"),
        spaceAfter=2
    )
    sub_brand_style = ParagraphStyle(
        "SubBrandHeader",
        parent=styles["Normal"],
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=colors.HexColor("#0d9488"),
        spaceAfter=12
    )
    section_title_style = ParagraphStyle(
        "SectionTitle",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=15,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=12,
        spaceAfter=6
    )
    normal_small = ParagraphStyle(
        "NormalSmall",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#334155")
    )

    # 1. Title & Header
    report_type_title = report_metadata.get("report_type", "EXPOSURE MONITORING REPORT").upper()
    story.append(Paragraph("SENTRIDOSE", brand_style))
    story.append(Paragraph(f"PASSIVE EXPOSURE DOSIMETER — {report_type_title}", sub_brand_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0d9488"), spaceAfter=10))

    # Metadata Grid (Report ID, Period, Generated By/At)
    meta_table_data = [
        [
            Paragraph(f"<b>Report ID:</b> {report_metadata.get('report_id', 'RPT-000001')}", normal_small),
            Paragraph(f"<b>Report Period:</b> {report_metadata.get('period', 'N/A')}", normal_small)
        ],
        [
            Paragraph(f"<b>Generated By:</b> {report_metadata.get('generated_by', 'Supervisor')}", normal_small),
            Paragraph(f"<b>Generated At:</b> {report_metadata.get('generated_at', 'N/A')}", normal_small)
        ]
    ]
    t_meta = Table(meta_table_data, colWidths=[270, 270])
    t_meta.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
        ('PADDING', (0,0), (-1,-1), 6),
        ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t_meta)
    story.append(Spacer(1, 10))

    # 2. Applied Filters
    filter_strs = []
    if filters.get("start_date") and filters.get("end_date"):
        filter_strs.append(f"<b>Date:</b> {filters['start_date']} to {filters['end_date']}")
    if filters.get("department_name"):
        filter_strs.append(f"<b>Department:</b> {filters['department_name']}")
    if filters.get("zone_name"):
        filter_strs.append(f"<b>Zone:</b> {filters['zone_name']}")
    if filters.get("shift_name"):
        filter_strs.append(f"<b>Shift:</b> {filters['shift_name']}")
    if filters.get("worker_name"):
        filter_strs.append(f"<b>Worker:</b> {filters['worker_name']} ({filters.get('worker_code', '')})")
    if filters.get("exposure_class") and filters.get("exposure_class") != "ALL":
        filter_strs.append(f"<b>Exposure Filter:</b> {filters['exposure_class']}")

    filter_text = " &nbsp;|&nbsp; ".join(filter_strs) if filter_strs else "All records within date range"
    story.append(Paragraph(f"<b>APPLIED FILTERS:</b> {filter_text}", normal_small))
    story.append(Spacer(1, 10))

    # 3. Summary Statistics Cards
    story.append(Paragraph("SUMMARY STATISTICS", section_title_style))
    summary_grid = [
        ["Total Workers", "Total Scans", "BASE", "LOW", "MEDIUM", "HIGH", "Attention Required"],
        [
            str(summary_data.get("total_workers", 0)),
            str(summary_data.get("total_scans", 0)),
            str(summary_data.get("base_count", 0)),
            str(summary_data.get("low_count", 0)),
            str(summary_data.get("medium_count", 0)),
            str(summary_data.get("high_count", 0)),
            str(summary_data.get("attention_required", 0))
        ]
    ]
    t_summary = Table(summary_grid, colWidths=[77, 77, 77, 77, 77, 77, 78])
    t_summary.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#1e293b")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('PADDING', (0,0), (-1,-1), 5),
        ('BACKGROUND', (0,1), (1,1), colors.HexColor("#f1f5f9")),
        ('BACKGROUND', (2,1), (2,1), colors.HexColor("#f8fafc")), # BASE
        ('BACKGROUND', (3,1), (3,1), colors.HexColor("#f0fdf4")), # LOW
        ('BACKGROUND', (4,1), (4,1), colors.HexColor("#fefce8")), # MEDIUM
        ('BACKGROUND', (5,1), (5,1), colors.HexColor("#fef2f2")), # HIGH
        ('BACKGROUND', (6,1), (6,1), colors.HexColor("#fff1f2")), # Attention
        ('TEXTCOLOR', (4,1), (4,1), colors.HexColor("#854d0e")),
        ('TEXTCOLOR', (5,1), (5,1), colors.HexColor("#991b1b")),
        ('TEXTCOLOR', (6,1), (6,1), colors.HexColor("#be123c")),
        ('FONTNAME', (0,1), (-1,1), 'Helvetica-Bold'),
        ('FONTSIZE', (0,1), (-1,1), 10),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
    ]))
    story.append(t_summary)
    story.append(Spacer(1, 14))

    # 4. Exposure Distribution Summary
    story.append(Paragraph("EXPOSURE DISTRIBUTION", section_title_style))
    dist_data = [
        ["Class", "Description", "Scan Count", "Percentage"],
        ["BASE", "Baseline Optical Reference", str(summary_data.get("base_count", 0)), f"{summary_data.get('base_pct', 0.0):.1f}%"],
        ["LOW", "Low Relative Colorimetric Shift", str(summary_data.get("low_count", 0)), f"{summary_data.get('low_pct', 0.0):.1f}%"],
        ["MEDIUM", "Medium Risk Shift — Supervisor Notification Triggered", str(summary_data.get("medium_count", 0)), f"{summary_data.get('medium_pct', 0.0):.1f}%"],
        ["HIGH", "High Risk Critical Shift — Supervisor Alert Triggered", str(summary_data.get("high_count", 0)), f"{summary_data.get('high_pct', 0.0):.1f}%"],
    ]
    t_dist = Table(dist_data, colWidths=[65, 275, 100, 100])
    t_dist.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#334155")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('PADDING', (0,0), (-1,-1), 4),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ('FONTSIZE', (0,1), (-1,-1), 8),
        ('TEXTCOLOR', (0,3), (-1,3), colors.HexColor("#854d0e")),
        ('TEXTCOLOR', (0,4), (-1,4), colors.HexColor("#991b1b")),
    ]))
    story.append(t_dist)
    story.append(Spacer(1, 14))

    # 5. Detailed Scan Records
    story.append(Paragraph("DETAILED SCAN RECORDS", section_title_style))
    
    headers = ["Scan ID", "Date / Time", "Worker & Code", "Dept / Zone / Shift", "Exposure", "Conf.", "Delta E", "Risk Status"]
    table_rows = [headers]

    for s in scans_data:
        exp = s.get("exposure_class", "BASE")
        exp_color = "#475569"
        if exp == "LOW":
            exp_color = "#15803d"
        elif exp == "MEDIUM":
            exp_color = "#b45309"
        elif exp == "HIGH":
            exp_color = "#b91c1c"

        exp_p = Paragraph(f"<font color='{exp_color}'><b>{exp}</b></font>", normal_small)
        worker_p = Paragraph(f"<b>{s.get('worker_name', '')}</b><br/><font color='#64748b'>{s.get('worker_code', '')}</font>", normal_small)
        dept_p = Paragraph(f"{s.get('department_name', '')}<br/><font color='#64748b'>{s.get('zone_name', '')} | {s.get('shift_name', '')}</font>", normal_small)
        
        status_str = s.get("risk_status", "NORMAL")
        status_p = Paragraph(f"<font color='{exp_color}'><b>{status_str}</b></font>", normal_small)

        table_rows.append([
            str(s.get("id")),
            s.get("timestamp_fmt", ""),
            worker_p,
            dept_p,
            exp_p,
            f"{s.get('confidence', 0)*100:.1f}%",
            f"{s.get('delta_e', 0):.2f}",
            status_p
        ])

    t_scans = Table(table_rows, colWidths=[45, 80, 110, 135, 55, 45, 45, 65])
    t_scans.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0f172a")),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('PADDING', (0,0), (-1,-1), 4),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#e2e8f0")),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#f8fafc")]),
    ]))

    story.append(t_scans)
    doc.build(story, canvasmaker=NumberedCanvas)

    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def generate_csv_report(scans_data: List[Dict[str, Any]]) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    
    writer.writerow([
        "Scan ID", "Date", "Time", "Worker ID", "Worker Name", "Worker Code",
        "Department", "Zone", "Shift", "Exposure Class", "Nearest Shade",
        "Scanned Hex", "Reference Hex", "Confidence", "ML Confidence",
        "Delta E", "Model Used", "Status"
    ])

    for s in scans_data:
        writer.writerow([
            s.get("id"),
            s.get("date_str"),
            s.get("time_str"),
            s.get("worker_id"),
            s.get("worker_name"),
            s.get("worker_code"),
            s.get("department_name"),
            s.get("zone_name"),
            s.get("shift_name"),
            s.get("exposure_class"),
            s.get("nearest_shade"),
            s.get("scanned_hex"),
            s.get("reference_hex"),
            f"{s.get('confidence', 0)*100:.2f}%",
            f"{s.get('ml_confidence', 0)*100:.2f}%",
            s.get("delta_e"),
            s.get("model_used"),
            s.get("risk_status", "NORMAL")
        ])

    return output.getvalue()


def generate_excel_report(
    report_metadata: Dict[str, Any],
    summary_data: Dict[str, Any],
    scans_data: List[Dict[str, Any]],
    worker_summary: List[Dict[str, Any]],
    zone_summary: List[Dict[str, Any]],
    risk_events: List[Dict[str, Any]]
) -> bytes:
    wb = openpyxl.Workbook()
    wb.remove(wb.active)

    font_header = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    fill_header = PatternFill(start_color="0F172A", end_color="0F172A", fill_type="solid")

    # Sheet 1: Summary
    ws1 = wb.create_sheet(title="Summary")
    ws1.append(["SENTRIDOSE EXPOSURE MONITORING REPORT"])
    ws1.append([f"Report ID: {report_metadata.get('report_id')}", f"Period: {report_metadata.get('period')}"])
    ws1.append([f"Generated By: {report_metadata.get('generated_by')}", f"Generated At: {report_metadata.get('generated_at')}"])
    ws1.append([])

    ws1.append(["EXPOSURE METRIC", "VALUE"])
    ws1.append(["Total Workers Monitored", summary_data.get("total_workers", 0)])
    ws1.append(["Total Dosimeter Scans", summary_data.get("total_scans", 0)])
    ws1.append(["BASE Scans", summary_data.get("base_count", 0)])
    ws1.append(["LOW Risk Scans", summary_data.get("low_count", 0)])
    ws1.append(["MEDIUM Risk Alerts", summary_data.get("medium_count", 0)])
    ws1.append(["HIGH Critical Risk Alerts", summary_data.get("high_count", 0)])
    ws1.append(["Attention Required Total", summary_data.get("attention_required", 0)])

    # Sheet 2: Scan Records
    ws2 = wb.create_sheet(title="Scan Records")
    headers2 = [
        "Scan ID", "Date", "Time", "Worker ID", "Worker Name", "Worker Code",
        "Department", "Zone", "Shift", "Exposure Class", "Nearest Shade",
        "Scanned Hex", "Reference Hex", "Confidence", "ML Confidence",
        "Delta E", "Model Used", "Risk Status"
    ]
    ws2.append(headers2)
    for s in scans_data:
        ws2.append([
            s.get("id"),
            s.get("date_str"),
            s.get("time_str"),
            s.get("worker_id"),
            s.get("worker_name"),
            s.get("worker_code"),
            s.get("department_name"),
            s.get("zone_name"),
            s.get("shift_name"),
            s.get("exposure_class"),
            s.get("nearest_shade"),
            s.get("scanned_hex"),
            s.get("reference_hex"),
            s.get("confidence"),
            s.get("ml_confidence"),
            s.get("delta_e"),
            s.get("model_used"),
            s.get("risk_status", "NORMAL")
        ])

    # Sheet 3: Risk Events
    ws3 = wb.create_sheet(title="Risk Events")
    headers3 = [
        "Scan ID", "Date", "Time", "Worker Name", "Worker Code",
        "Department", "Zone", "Shift", "Severity", "Confidence",
        "Acknowledgement Status", "Acknowledged At", "Acknowledged By"
    ]
    ws3.append(headers3)
    for r in risk_events:
        ws3.append([
            r.get("scan_id"),
            r.get("date_str"),
            r.get("time_str"),
            r.get("worker_name"),
            r.get("worker_code"),
            r.get("department_name"),
            r.get("zone_name"),
            r.get("shift_name"),
            r.get("severity"),
            r.get("confidence"),
            "ACKNOWLEDGED" if r.get("is_acknowledged") else "OPEN",
            r.get("acknowledged_at_fmt", "N/A"),
            r.get("acknowledged_by", "N/A")
        ])

    # Sheet 4: Worker Summary
    ws4 = wb.create_sheet(title="Worker Summary")
    ws4.append(["Worker Name", "Worker Code", "Department", "Zone", "Total Scans", "BASE", "LOW", "MEDIUM", "HIGH", "Risk Alert Count"])
    for w in worker_summary:
        ws4.append([
            w.get("name"),
            w.get("worker_code"),
            w.get("department"),
            w.get("zone"),
            w.get("total_scans"),
            w.get("base_count"),
            w.get("low_count"),
            w.get("medium_count"),
            w.get("high_count"),
            w.get("risk_count")
        ])

    # Sheet 5: Zone Summary
    ws5 = wb.create_sheet(title="Zone Summary")
    ws5.append(["Department", "Zone Name", "Zone Code", "Total Workers", "Total Scans", "BASE", "LOW", "MEDIUM", "HIGH", "Attention Count"])
    for z in zone_summary:
        ws5.append([
            z.get("department_name"),
            z.get("zone_name"),
            z.get("zone_code"),
            z.get("total_workers"),
            z.get("total_scans"),
            z.get("base_count"),
            z.get("low_count"),
            z.get("medium_count"),
            z.get("high_count"),
            z.get("attention_count")
        ])

    for ws in wb.worksheets:
        for col in ws.columns:
            max_len = max(len(str(cell.value or '')) for cell in col)
            col_letter = get_column_letter(col[0].column)
            ws.column_dimensions[col_letter].width = max(max_len + 3, 12)
        
        for cell in ws[1]:
            cell.font = font_header
            cell.fill = fill_header
            cell.alignment = Alignment(horizontal="center", vertical="center")

    buffer = io.BytesIO()
    wb.save(buffer)
    excel_bytes = buffer.getvalue()
    buffer.close()
    return excel_bytes
